<?php $helper = Mage::helper('stickyproductsidebar'); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php if (!$helper->isEnableProduct()): ?>
    <div class="sticky-sidebar">
        <button class="close" data-action='stop'>X</button>
        <h4 class="sticky-head"><?php echo $this->__('Currently Viewing') ?></h4>
        <div class="product-shop">
            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
            <div class="product-name">
                 <h4> <?php echo Mage::helper('core/string')->truncate($_product->getName(), 150, '...');?> </h4>
            </div>
            <?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
            <div class="desc std">
                <?php echo Mage::helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 150, '...');
                ?>
            </div>
            <?php if (!$this->hasOptions() && !$_product->isGrouped()): ?>
                <?php if ($_product->isSaleable()): ?>
                    <p><button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span class="stickybuy-icon"></span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                <?php else: ?>
                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                <?php endif; ?>
            <?php endif; ?>

        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            var stickEm = jQuery('.sticky-sidebar').stickEmUp({
                stickOffset: -<?php echo $helper->getHeight();?>,
                callback: function (info) {
                    console.log(info);
                },
            }).data('plugin_stickEmUp');

            jQuery('[data-action="stop"]').click(function () {
                stickEm.disableSticky();
            });
        });
    </script>
<?php else: ?>
    <div class="sticky-sidebar-horizontal">
        <div class="inner">
            <div class="image">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(50); ?>" width="50" height="50" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></div>
            <div class="desc std">
                <?php echo Mage::helper('core/string')->truncate($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 150, '...');
                ?>
            </div>
            <?php echo $this->getPriceHtml($_product, true) ?>
            <div class="add-to-cart">
                <?php if (!$this->hasOptions() && !$_product->isGrouped()): ?>
                    <?php if ($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                <?php endif; ?>
            </div>
            <div class="close-btn">
                <button class="close" data-action-horizontal='stop'>X</button>
            </div>
            <div class="clr"></div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function () {
            /* horizontal */
            var stickEmHorizontal = jQuery('.sticky-sidebar-horizontal').stickEmUp({
                stickOffset: -<?php echo $helper->getHeight();?>,
                stickyClass: 'stickEmUpHorizontal',
                callback: function (info) {
                    console.log(info);
                },
            }).data('plugin_stickEmUp');

            jQuery('[data-action-horizontal="stop"]').click(function () {
                stickEmHorizontal.disableSticky();
            });
        });
    </script>
<?php endif; ?>